# Generated by Django 4.2.17 on 2024-12-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password' , models.CharField(max_length=8)),
                ('repeat_password ', models.CharField(max_length=8)),
                ('age' , models.IntegerField()),
            ],
        ),
    ]
